server:
  port : 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  mandatory-file-encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5455/Geek
    username: kekNya
    password: f8wy3dmi
    driver-class-name: org.postgresql.Driver

#spring:
#  data:
#    mongodb:
#      port: 27017
#      host: localhost
#      database: GeekBrains
#      password: f8wy3dmi
#      username: mongo
#      authentication-database: admin

