server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  mandatory-file-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  datasource:
    url: YOUR_URL
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver

  #datasource:
  #  url: jdbc:h2:mem:test
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver