CREATE TABLE products
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR,
    description VARCHAR,
    price       INTEGER,
    image       VARCHAR,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

DROP TABLE IF EXISTS products;