DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS bought_product;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS orders_products;

CREATE TABLE users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       INTEGER,
    image       VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE bought_product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    price      BIGINT,
    CONSTRAINT pk_bought_product PRIMARY KEY (id)
);

ALTER TABLE bought_product
    ADD CONSTRAINT FK_BOUGHT_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE TABLE orders
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE orders_products
(
    order_id    BIGINT NOT NULL,
    products_id BIGINT NOT NULL
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders_products
    ADD CONSTRAINT fk_ordpro_on_bought_product FOREIGN KEY (products_id) REFERENCES bought_product (id);

ALTER TABLE orders_products
    ADD CONSTRAINT fk_ordpro_on_order FOREIGN KEY (order_id) REFERENCES orders (id);