server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
            - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/okon-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/okon-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/okon-auth
            - JwtAuthFilter