server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    context-path: /okon-cart

spring:
  mandatory-file-encoding: UTF-8

integrations:
  product-service:
    baseUrl: http://localhost:8081/okon-core/api/products
    connectionTimeout: 1000
    readTimeout: 1000
    writeTimeout: 1000
